### ISSUE TITLE
Could you provide the pre-trained models on the nuscenes dataset and waymo dataset?

### ISSUE THREAD

**Issue by Devoe-97** [agent-sgs/PillarNet#1]
Very awesome work! 
Could you provide the pre-trained models on the nuscenes dataset and waymo dataset?

**Comment by Number1JT** [comment]
can you provide config file to reproduce the reported performance (Vehicle mAP  79.09) on waymo?

**Comment by Number1JT** [comment]
@agent-sgs

**Comment by Number1JT** [comment]
@agent-sgs thanks for reply. Can you provide config file that can reproduce the reported performance on waymo(83.23/82.80 vehicle AP/APH)?
