### ISSUE TITLE
nms_IOU is not working with vehicle class

### ISSUE THREAD

**Issue by YoushaaMurhij** [agent-sgs/PillarNet#10]
I am using this WAYMO [config](https://github.com/agent-sgs/PillarNet/blob/master/configs/waymo/voxelnet/waymo_centerpoint_pillarnet_3x.py) to run inference but there are overlaped boxes on every car, as seen in the screenshot. I am using the default config without any changes. Even If I modify the nms parameters, I still get the same results. Everything is fine with pedestrian and cyclist classes. 

Any suggestions?
Thanks.

![Screenshot from 2022-07-29 15-01-02](https://user-images.githubusercontent.com/16229594/181756048-a9ad2caf-a3ac-4685-a686-72b72ca8b4fe.png)

**Comment by agent-sgs** [comment]
You can chat me with WeChat for the ambiguous problem
