### ISSUE TITLE
what is divide task ["Vehicle", "Pedestrain", "Cyclist"] -> ["Vehicle"] , ["Pedestrain", "Cyclist"]

### ISSUE THREAD

**Issue by lejk8104** [agent-sgs/PillarNet#11]
thanks your fully support about PIllarNet

I am conduct into training PillarNet model reference of your github page. (same config and setting)
but some difference about CenterPoint-voxel config file.

pillarnet path: /configs/waymo/voxelnet/waymo_centerpoint_pillarnet_3x.py
`tasks = [
    dict(stride=8, class_names=['VEHICLE']),
    dict(stride=8, class_names=['PEDESTRIAN', 'CYCLIST'])]
class_names = list(itertools.chain(*[t["class_names"] for t in tasks]))`

centerpoint path: configs/waymo/voxelnet/waymo_centerpoint_voxelnet_3x.py
`tasks = [
    dict(num_class=3, class_names=['VEHICLE', 'PEDESTRIAN', 'CYCLIST']),]
class_names = list(itertools.chain(*[t["class_names"] for t in tasks]))`

1. why is difference about config file?
2. GPU mermory changed frequently during training Pillarnet
![Screenshot from 2022-08-03 14-25-09](https://user-images.githubusercontent.com/41908895/182530698-6329ce44-519b-4319-b9d4-84bf509df5a8.png)
![Screenshot from 2022-08-03 14-25-20](https://user-images.githubusercontent.com/41908895/182530712-dca4643e-581e-439e-b862-a3297f2d2f08.png)
![Screenshot from 2022-08-03 14-25-48](https://user-images.githubusercontent.com/41908895/182530754-194e3929-6962-45ad-a27b-5feaee03a1b7.png)
it is general case? is not negative effect about Pillarnet accuracy? or training?

**Comment by agent-sgs** [comment]
You can also use the same config without division for the same results
The division is for the next work
