### ISSUE TITLE
Performances of config waymo_centerpoint_pillarnet_3x.py

### ISSUE THREAD

**Issue by chunk425015** [agent-sgs/PillarNet#13]
Hi,
I am going to make some exploration based on your wonderful work. Since you only provide the single config `waymo_centerpoint_pillarnet_3x.py` for WOD, I am curious about its performance. Can it reproduce your best single frame performance reported on your paper? (79.09 L1 Vehicle mAP)

**Comment by agent-sgs** [comment]
Yeah, you can easily reproduce the reported results using the provided config with IoU branch and its related hyper-parameters to
