### ISSUE TITLE
About the deployment

### ISSUE THREAD

**Issue by wcshen** [agent-sgs/PillarNet#19]
Because the sparse conv is not supported in the onnx, so i think the origin PillarNet with sparse conv backbone is not friendly for the deployment.
So, if we change the sparse conv backbone to the normal conv backbone, what is the impact on model performance and inference speed?

**Comment by agent-sgs** [comment]
We believe that one big progress for point cloud detection domain is the sparse convolution. It can be verified that serveral china high-tech companies have developped the TensorRT for the sparse convolutions.

**Comment by wcshen** [comment]
> We believe that one big progress for point cloud detection domain is the sparse convolution. It can be verified that serveral china high-tech companies have developped the TensorRT for the sparse convolutions.

Can you tell me which companies are?
