### ISSUE TITLE
bbox3d_overlaps_iou calculation wrong?

### ISSUE THREAD

**Issue by DeclK** [agent-sgs/PillarNet#3]
https://github.com/agent-sgs/PillarNet/blob/fdf62369846fc8c919295955887059307c52f934/det3d/core/utils/center_utils.py#L133-L141

I think the iou calculation here is not right? There are 2 `maximum` operation, but the first `maximum` should be `minimum`?

**Comment by agent-sgs** [comment]
We thank your careful comments.

**Comment by agent-sgs** [comment]
We thank your comment. Also, we have released the carefully organized version.
