### ISSUE TITLE
Questions about config file

### ISSUE THREAD

**Issue by mc171819** [agent-sgs/PillarNet#5]
Hi, PillarNet is a wonderful work. However, I found the config file in this project seems the same one like Centerpoint. When will you release the config file to train PillarNet? Or if I have a wrong understanding, which config file should I refer to?

**Comment by agent-sgs** [comment]
To be fairly compared with CenterPoint-VoxelNet and CenterPoint-PointPillars, our PillarNet uses the same training schedule ([nusc_centerpoint_pillarnet_h.py](https://github.com/agent-sgs/PillarNet/blob/master/configs/nusc/voxelnet/nusc_centerpoint_pillarnet_h.py)) and hyper-parameters with CenterPoint-VoxelNet ([nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py](https://github.com/agent-sgs/PillarNet/blob/master/configs/nusc/voxelnet/nusc_centerpoint_voxelnet_0075voxel_fix_bn_z.py)).
The only difference is to apply our backbone and lossless pillarization.
