### ISSUE TITLE
Why are the IoU-score rectifiers set to zero?

### ISSUE THREAD

**Issue by Abyssaledge** [agent-sgs/PillarNet#7]
Wonderful work!
When I go through the config `waymo_centerpoint_pillarnet_3x.py`, I found the rectifier the test_cfg are set to zero, which indicates the predicted IoUs are not used.  
Any special consideration to disable the rectification?

**Comment by agent-sgs** [comment]
You can find the best parameter rather than the commented rectifier. In paper, we just apply these hyper-parameters from AVDetV2 (not the best for PillarNet) for comparison.
