### ISSUE TITLE
some question about table1 and table4

### ISSUE THREAD

**Issue by AndyYuan96** [agent-sgs/PillarNet#8]
Hi, thanks for open source the project, I have some question about table1 and table4's result, why in table4, PillarNet-18's result is similar with centerpoint-second, but in table1, PillarNet-18's performance is so high compared with centerpoint-second. Table1 is test set result, Table4 is valset result, generally Table1's result should lower than Table4's result, centerpoint-second follow the common sense， but why pillarnet-18's test set result is so high compared with val set?
What‘s more, can I ask which one is pillarnet in nus leaderboard, as I don't find pillarnet name.

**Comment by agent-sgs** [comment]
I have released the results on nuScenes leaderboard that may be not officially updated immediately.
You can refer to the results of PillarNet-34 advancely https://eval.ai/challenge/356/leaderboard/1012
